ECS Service and cluster scaling
skyscrapers/terraform-ecs pull request #6
Opened 2017-08-10 13:16 UTC by ThomasVdBerge

## Description
Added module to simplify the adding of ECS service/cluster scaling.

## Related Issue

https://github.com/skyscrapers/diekeure/issues/65

## Motivation and Context
```
+ module.service-scaling.aws_appautoscaling_policy.scale_down
    adjustment_type:                                        "ChangeInCapacity"
    arn:                                                    "<computed>"
    cooldown:                                               "60"
    metric_aggregation_type:                                "Maximum"
    name:                                                   "default-test-service-scale-in"
    policy_type:                                            "StepScaling"
    resource_id:                                            "service/test/test"
    scalable_dimension:                                     "ecs:service:DesiredCount"
    service_namespace:                                      "ecs"
    step_adjustment.#:                                      "1"
    step_adjustment.2173517692.metric_interval_lower_bound: ""
    step_adjustment.2173517692.metric_interval_upper_bound: "0"
    step_adjustment.2173517692.scaling_adjustment:          "-1"

+ module.service-scaling.aws_appautoscaling_policy.scale_up
    adjustment_type:                                        "ChangeInCapacity"
    arn:                                                    "<computed>"
    cooldown:                                               "60"
    metric_aggregation_type:                                "Maximum"
    name:                                                   "default-test-service-scale-out"
    policy_type:                                            "StepScaling"
    resource_id:                                            "service/test/test"
    scalable_dimension:                                     "ecs:service:DesiredCount"
    service_namespace:                                      "ecs"
    step_adjustment.#:                                      "1"
    step_adjustment.3459629261.metric_interval_lower_bound: ""
    step_adjustment.3459629261.metric_interval_upper_bound: "0"
    step_adjustment.3459629261.scaling_adjustment:          "1"

+ module.service-scaling.aws_appautoscaling_target.ecs_target
    max_capacity:       "10"
    min_capacity:       "2"
    resource_id:        "service/test/test"
    role_arn:           "${aws_iam_role.ecs-autoscale-role.arn}"
    scalable_dimension: "ecs:service:DesiredCount"
    service_namespace:  "ecs"

+ module.service-scaling.aws_autoscaling_policy.ecs_cluster_scale_in
    adjustment_type:         "PercentChangeInCapacity"
    arn:                     "<computed>"
    autoscaling_group_name:  "ecs-cluster-test"
    cooldown:                "300"
    metric_aggregation_type: "<computed>"
    name:                    "default-test-cluster-scale-in"
    policy_type:             "SimpleScaling"
    scaling_adjustment:      "-50"

+ module.service-scaling.aws_autoscaling_policy.ecs_cluster_scale_out
    adjustment_type:         "PercentChangeInCapacity"
    arn:                     "<computed>"
    autoscaling_group_name:  "ecs-cluster-test"
    cooldown:                "300"
    metric_aggregation_type: "<computed>"
    name:                    "default-test-cluster-scale-out"
    policy_type:             "SimpleScaling"
    scaling_adjustment:      "100"

+ module.service-scaling.aws_cloudwatch_metric_alarm.ecs_cluster_scale_in_alarm
    actions_enabled:                       "true"
    alarm_actions.#:                       "<computed>"
    alarm_description:                     "This metric monitor ecs CPU utilization down"
    alarm_name:                            "default-test-ECSClusterScaleInAlarm"
    comparison_operator:                   "LessThanOrEqualToThreshold"
    dimensions.%:                          "1"
    dimensions.ClusterName:                "test"
    evaluate_low_sample_count_percentiles: "<computed>"
    evaluation_periods:                    "4"
    metric_name:                           "CPUReservation"
    namespace:                             "AWS/ECS"
    period:                                "120"
    statistic:                             "Average"
    threshold:                             "25"
    treat_missing_data:                    "missing"

+ module.service-scaling.aws_cloudwatch_metric_alarm.ecs_cluster_scale_out_alarm
    actions_enabled:                       "true"
    alarm_actions.#:                       "<computed>"
    alarm_description:                     "This metric monitor ecs CPU utilization up"
    alarm_name:                            "default-test-ECSClusterScaleOutAlarm"
    comparison_operator:                   "GreaterThanOrEqualToThreshold"
    dimensions.%:                          "1"
    dimensions.ClusterName:                "test"
    evaluate_low_sample_count_percentiles: "<computed>"
    evaluation_periods:                    "4"
    metric_name:                           "CPUReservation"
    namespace:                             "AWS/ECS"
    period:                                "120"
    statistic:                             "Average"
    threshold:                             "75"
    treat_missing_data:                    "missing"

+ module.service-scaling.aws_cloudwatch_metric_alarm.ecs_service_scale_in_alarm
    actions_enabled:                       "true"
    alarm_actions.#:                       "<computed>"
    alarm_description:                     "This metric monitor ecs CPU utilization down"
    alarm_name:                            "default-test-ECSServiceScaleInAlarm"
    comparison_operator:                   "LessThanOrEqualToThreshold"
    dimensions.%:                          "2"
    dimensions.ClusterName:                "test"
    dimensions.ServiceName:                "test"
    evaluate_low_sample_count_percentiles: "<computed>"
    evaluation_periods:                    "4"
    metric_name:                           "CPUUtilization"
    namespace:                             "AWS/ECS"
    period:                                "120"
    statistic:                             "Average"
    threshold:                             "25"
    treat_missing_data:                    "missing"

+ module.service-scaling.aws_cloudwatch_metric_alarm.ecs_service_scale_out_alarm
    actions_enabled:                       "true"
    alarm_actions.#:                       "<computed>"
    alarm_description:                     "This metric monitor ecs CPU utilization up"
    alarm_name:                            "default-test-ECSServiceScaleOutAlarm"
    comparison_operator:                   "GreaterThanOrEqualToThreshold"
    dimensions.%:                          "2"
    dimensions.ClusterName:                "test"
    dimensions.ServiceName:                "test"
    evaluate_low_sample_count_percentiles: "<computed>"
    evaluation_periods:                    "4"
    metric_name:                           "CPUUtilization"
    namespace:                             "AWS/ECS"
    period:                                "120"
    statistic:                             "Average"
    threshold:                             "75"
    treat_missing_data:                    "missing"

+ module.service-scaling.aws_iam_role.ecs-autoscale-role
    arn:                "<computed>"
    assume_role_policy: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"application-autoscaling.amazonaws.com\"\n      },\n      \"Effect\": \"Allow\"\n    }\n  ]\n}\n"
    create_date:        "<computed>"
    name:               "ecs-scale-default-test"
    path:               "/"
    unique_id:          "<computed>"

+ module.service-scaling.aws_iam_role_policy_attachment.ecs_autoscale
    policy_arn: "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole"
    role:       "${aws_iam_role.ecs-autoscale-role.id}"

+ mo [...]

2017-08-10 13:50 UTC, venturel requested changes

2017-08-10 13:50 UTC, venturel commented on scaling/main.tf
> +  scaling_adjustment     = -50
Would it be possible to create a var with default vallue for this?

2017-08-10 13:50 UTC, venturel commented on scaling/main.tf
> +  scaling_adjustment     = 100
also for this

2017-08-10 13:50 UTC, venturel commented on scaling/main.tf
> +  threshold           = "75"
also for this

2017-08-10 13:50 UTC, venturel commented on scaling/main.tf
> +  threshold           = "25"
and this

2017-08-10 13:50 UTC, venturel commented on scaling/main.tf
> +    scaling_adjustment          = "-1"
and this

2017-08-10 13:50 UTC, venturel commented on scaling/main.tf
> +    scaling_adjustment          = "1"
and this

2017-08-10 13:50 UTC, venturel commented on README.md
> + * [`service_name`]: String(required): The name of the ECS cluster.
not sure this is the right description

2017-08-10 13:50 UTC, venturel commented on scaling/main.tf
> +  threshold           = "75"
Would it be possible to create a var with default vallue for this?

2017-08-10 13:50 UTC, venturel commented on scaling/main.tf
> +  threshold           = "25"
also here

2017-08-10 13:50 UTC, venturel commented on scaling/variables.tf
> +  description = "Name of the service"
I'd change or remove the description

2017-08-10 13:54 UTC, venturel commented
Also @ThomasVdBerge why don't you use the scale module for the instance autoscaling? And you call scale in/out and scale up/down. Would it be possible to use just one of them? Personally I prefer up/down.

2017-08-11 08:51 UTC, ringods requested changes

2017-08-11 08:51 UTC, ringods commented on scaling/iam.tf
> +  name = "ecs-scale-${terraform.env}-${var.cluster_name}"
If this module is aimed at configuring the service auto scaling, do not create cluster specific resources in this module. Trying to call this module to configure the service scaling for two services on the same cluster will lead to an error when calling it the second time as the name is already taken. The cluster resources should be created when in the module setting up the ECS cluster.

2017-08-11 09:28 UTC, ThomasVdBerge commented on scaling/iam.tf
> +  name = "ecs-scale-${terraform.env}-${var.cluster_name}"
You're right, the var cluster should not be in here

2017-08-11 11:56 UTC, ringods commented on scaling/iam.tf
> +  name = "ecs-scale-${terraform.env}-${var.cluster_name}"
@ThomasVdBerge you didn't fix the naming of the iam resources with your last commit, so my initial remark is still valid. ;-)

2017-08-11 12:05 UTC, ringods approved these changes

2017-08-11 12:58 UTC, venturel approved these changes

2017-08-11 12:59 UTC, merged